### ISSUE TITLE
CPP crashes HIE

### ISSUE THREAD

**Issue by fendor** [mpickering/haskell-ide-engine#24]
It works as long as CPP is correct, but as soon as a single change results in an invalid CPP instruction, hie crashes

**Comment by fendor** [comment]
@mpickering 
logs for editing a file with cpp:
https://gist.github.com/fendor/29219cfecc9a17034110c608ced9ac3e
Last line contains the error.

**Comment by mpickering** [comment]
Also need to add a test for this situation.

**Comment by mpickering** [comment]
I wrote a simple failing test for what I believe the error is?

https://github.com/mpickering/haskell-ide-engine/commit/7fd163269e04c7660c1977a08ece4f5c19a0b52d

**Comment by fendor** [comment]
Looks good to show the error! But the test can't succeed in our current implementation, because the error is thrown in runActionWithContext, or loadCradle, which is unable to produce diagnostics and can only report errors via errorLogS in errorHandler, which has been given by LspStdio to Scheduler as a callback.

To work around this issue for a test case, we design a test case with code that is valid in the beginning and modify the test code to contain an invalid cpp expression. I tried to implement a test case, but could not create reliable test assertions, yet.

**Comment by fendor** [comment]
Closed by #19
