### ISSUE TITLE
Work out how to support the none cradle 

### ISSUE THREAD

**Issue by mpickering** [mpickering/haskell-ide-engine#38]
I was looking into how to support the "none" cradle and it seems a little bit tricky to implement.

Essentially we just want to completely ignore any files which are in a none cradle but the immediate issue is that `runActionWithContext` takes an action as a argument and either expects the result of this action to be returned or an `IdeResultFail`. 

Really `IdeResultFail` is not right still? because the IDE will still keep trying to load the `.hs` file into the session and the client will keep sending requests such as hover.

So we need to also inform the client that we're not going to handle this file so don't send us any requests.

**Comment by fendor** [comment]
closed by #40
