### ISSUE TITLE
Bad uses of readTVarIO

### ISSUE THREAD

**Issue by mpickering** [mpickering/haskell-ide-engine#45]
Using TVars rather than MVars opened up a lot of potential races. 

- [x] `runDeferredActions` - `readMTS` and `modifyMTS` = RACE
- [x] `HasGhcModuleCache` API in terms of get/set is unsafe (see IdeM implementation)
- [x] `hh` function in `haskell-lsp` - Read followed by modify
- [x] `handleMessageWithConfigChange` - Read followed by modify
- [x] `publishDiagnostics` - read/write could clobber update
- [x] `flushDiagnosticsBySouce` read/write
- [x] `initializeRequestHandler` read/write

**Comment by mpickering** [comment]
Most of these fixes are here https://github.com/alanz/haskell-lsp/pull/199

**Comment by mpickering** [comment]
Fix for `HasGhcModuleCache` is here - https://github.com/mpickering/haskell-ide-engine/pull/44/commits/d228c02d5bdb2395167b8c1b181c1550360f5eb6

**Comment by fendor** [comment]
Close as all of these have been merged.
