### ISSUE TITLE
Temp object file issue

### ISSUE THREAD

**Issue by mpickering** [mpickering/haskell-ide-engine#50]
CC @fendor 

Is this GHC issue similar to the problem you see with temporary object files ?https://gitlab.haskell.org/ghc/ghc/issues/12983

**Comment by fendor** [comment]
No, I dont think so. Whenever I saw error messages such as https://gist.github.com/fendor/35e7c50cc97d7b098c4bd683306b9a23, no template haskell was related or additional import, afaik.
Also, there was no explicit GHC panic.

**Comment by fendor** [comment]
Closed in favour of https://github.com/haskell/haskell-ide-engine/issues/1520
