### ISSUE TITLE
Apply hlint refactor remove unrelated code

### ISSUE THREAD

**Issue by jneira** [mpickering/haskell-ide-engine#77]
* From #73, i create a new one cause are two unrelated issues

When i tried to aplly the refactor using the light bulb:

![hie-bad-refactor](https://user-images.githubusercontent.com/54035/70461632-6c82ba00-1ab9-11ea-9256-dc764e11d9ff.gif)

It has removed imports and the function above the one with the redundant brackets (but it removed the brackets as well 😆 )

Maybe related #1448

**Comment by jneira** [comment]
I've collected some data about [here](https://gist.github.com/jneira/382b172f118d99ea1ced8e504197146c): 
* [relevant log traces](https://gist.github.com/jneira/382b172f118d99ea1ced8e504197146c#file-gistfile1-txt)
* [json message with the code edits formatted](https://gist.github.com/jneira/382b172f118d99ea1ced8e504197146c#file-edit-json)
* temp files [before](https://gist.github.com/jneira/382b172f118d99ea1ced8e504197146c#file-870452232-6-lib-hs-hs) and [after ](https://gist.github.com/jneira/382b172f118d99ea1ced8e504197146c#file-870452232-7-lib-hs-hs)the refactor

The temp files has unix line endings instead windows ones, so maybe it is related with the bug. Otoh other document changes (replace a unknown symbol or a typed hole) works wit actual line endings :thinking:

**Comment by jneira** [comment]
As @mpickering suggested i'll test it in master and i'll try to fix there if that is the case

**Comment by jneira** [comment]
Confirming the behavior is reproduced in master so i'll try to fix there.
Keeping the issue here, nevertheless, let me know if you prefer to move it to the main repo

**Comment by fendor** [comment]
Let's create a reference to it in master, so others can dig in and we can't accidentally forget it. Also, so that people can see that the bug is already known!

**Comment by jneira** [comment]
Closing this one here
