### ISSUE TITLE
hie.yaml/ghci for this repo

### ISSUE THREAD

**Issue by Avi-D-coder** [mpickering/haskell-ide-engine#87]
I'm trying to get `ghcide` or `stack ghci` to load this repo, but the `main module to load is ambiguous`.

```
CradleError (ExitFailure 1) [
The main module to load is ambiguous. Candidates are: 
1. Package `haskell-ide-engine' component haskell-ide-engine:exe:hie with main-is file: /home/host/Public/haskell-ide-engine/app/MainHie.hs
2. Package `haskell-ide-engine' component haskell-ide-engine:exe:hie-wrapper with main-is file: /home/host/Public/haskell-ide-engine/app/HieWrapper.hs
You can specify which one to pick by: 
 * Specifying targets to stack ghci e.g. stack ghci haskell-ide-engine:exe:hie
 * Specifying what the main is e.g. stack ghci --main-is haskell-ide-engine:exe:hie
 * Choosing from the candidate above [1..2]
]
* * * * * * * *

Specify main module to use (press enter to load none):
```

I would of thought something like `cradle: {stack: {component: "haskell-ide-engine:exe:hie"}}` would fix the issue, but it and `stack ghci haskell-ide-engine:exe:hie` produce:
```
<command line>: cannot satisfy -package z-haskell-ide-engine-z-hie-test-utils
    (use -v for more information)
```

**Comment by Avi-D-coder** [comment]
see the new section https://github.com/haskell/haskell-ide-engine#project-configuration

**Comment by fendor** [comment]
I don't think this is really solved. I can reproduce the problem but I think this is a stack problem.

**Comment by fendor** [comment]
https://github.com/commercialhaskell/stack/issues/4564 seems relevant
Stack does not support to load a project with `stack repl` if there are internal libraries.

**Comment by fendor** [comment]
Closing in favour of https://github.com/haskell/haskell-ide-engine/issues/1535
